### PR TITLE
CMake based build

### PR DESCRIPTION
**Pull request by jdswinbank**
Unfortunately, since we don't know how the user has installed DNest3 (but can assume it's not through a package manager), it's hard to make this completely bulletproof. I think this will do the right thing in most circumstances though.

By analogy with DNest3, I have build the executables in the source tree, and do not install them when you `make install`.

### CODE REVIEW

**Comment by eggplantbren** [comment]
Thanks John!

**Comment by eggplantbren** [comment]
Thanks John! I'll test it out and then merge assuming everything works well.

**Comment by mattpitkin** [comment]
I've added an issue related this this patch #2 (also I noticed that Brendon has changed all the Makefiles to use `-O3` rather than `-Ofast` - should this also be changed in the `CMakeLists.txt` file?)

**Comment by mattpitkin** [comment]
To make this a bit more agnostic to where DNest3 is installed the `FindDNest3.cmake` file could maybe have:

``` cmake
find_path (DNEST3_INCLUDES
    NAMES "MTSampler.h"
    PATHS /usr /usr/local /opt/local /sw
    PATH_SUFFIXES "/include" "include/dnest3"
    HINTS ${DNEST3_ROOT_DIR}
)

find_library (DNEST3_LIBRARY
    NAMES dnest3
    PATHS /usr /usr/local /opt/local /sw
    PATH_SUFFIXES "/lib"
    HINTS ${DNEST3_ROOT_DIR}
)
```

Although I don't know cmake at all well, so these maybe paths that are automatically searched anyway.

**Comment by jdswinbank** [comment]
CMake doesn't make it easy to find, but yes, it should be searching those paths by default. There's a description of the search algorithm at http://www.cmake.org/cmake/help/v3.3/command/find_library.html -- the relevant bit is step 5, "search cmake variables defined in the Platform files for the current system". I'm not sure if the contents of those platform files are actually documented anywhere, but it's easy enough to poke about in the source. On Darwin, they specifically include `/sw` and `/opt/local` among other things. Look for the files `Modules/Platform/Darwin.cmake` and `Modules/Platform/UnixPaths.cmake` in your CMake installation.

The rest of the suggestions here sound fine to me.

**Comment by mattpitkin** [comment]
Ah, yes! I see that in my `UnixPaths.cmake` file the defaults are `/usr/local`, `/usr` and `/`.

**Pull request merged**
